todolist/core/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.main, name="index"),
    path('tasks/', views.task_list, name="tasks"),
    path('tasks/save_task', views.save_task, name="save_task"),
    path('tasks/refresh_table', views.refresh_table, name="refresh_table"),
    path('tasks/delete_task', views.delete_task, name="delete_task"),
]

todolist/todolist/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
]

todolist/core/models.py
from django.db import models
from datetime import datetime

TASK_CATEGORIES = [
    ('W', 'Work'),
    ('P', 'Personal'),
    ('H', 'Health'),
    ('HM', 'Home'),
    ('S', 'School'),
    ('E', 'Errands'),
    ('FL', 'Family'),
    ('SC', 'Social'),
    ('HB', 'Hobbies'),
    ('G', 'General'),
]

TASK_STATUSES = [
    ('P','Pending'),
    ('I','In Progress'),
    ('C','Completed'),
    ('CC','Cancelled'),
    ('PP','Postponed'),
]

class Task(models.Model):

    title = models.CharField(max_length=30)
    description = models.TextField()
    category = models.CharField(choices=TASK_CATEGORIES)
    status = models.CharField(choices=TASK_STATUSES, default="P")
    user_id = models.IntegerField(default=1, blank=True, null=True)
    created_on = models.DateTimeField(datetime.now(), blank=True, null=True)
    updated_on = models.DateTimeField(blank=True, null=True, auto_now_add=True)

    def __str__(self):
        return self.title

todolist/core/views.py
from django.shortcuts import render
from .models import Task
from django.http import JsonResponse
from datetime import datetime
from django.db.models import Sum, Count, F, Value

TASK_CATEGORIES = {
    'W': 'Work',
    'P': 'Personal',
    'H': 'Health',
    'HM': 'Home',
    'S': 'School',
    'E': 'Errands',
    'FL': 'Family',
    'SC': 'Social',
    'HB': 'Hobbies',
    'G': 'General',
}

TASK_STATUSES = [
    ('P','Pending'),
    ('I','In-Progress'),
    ('C','Completed'),
    ('CC','Cancelled'),
    ('PP','Postponed'),
]


def main(request):

    summary = {}

    for status in TASK_STATUSES:
        summary[status[1]] = len(Task.objects.filter(status=status[0]))

    context = {
        'summary': summary
    }

    return render(request, 'index.html', context)


def task_list(request):
    tasks = Task.objects.all().order_by('-updated_on')
    context = {
        'tasks': tasks,
        'categories': TASK_CATEGORIES
    }
    return render(request, 'task_list.html', context)

def refresh_table(request):
    tasks = Task.objects.all().order_by('-updated_on')
    context = {
        'tasks': tasks,
    }

    return render(request, 'task_table.html', context)

def delete_task(request):

    task_id = request.POST.get('taskId')

    task = Task.objects.filter(id=task_id)
    task.delete()

    return JsonResponse({'message': 'Task deleted.'}, status=200)

def save_task(request):

    action = request.POST.get('action')
    task_id = request.POST.get('taskId')
    title = request.POST.get('title')
    description = request.POST.get('description')
    category = request.POST.get('category')

    created_on = datetime.now()
    updated_on = datetime.now()

    if action == 'Edit':
        task = Task.objects.filter(id=task_id)
        task.update(
            title=title,
            description=description,
            category=category,
            created_on=created_on,
            updated_on=updated_on,
        )
        
    else:
        task = Task(
            title=title,
            description=description,
            category=category,
            created_on=created_on,
            updated_on=updated_on,
        )
        task.save()

    return JsonResponse({'message': 'Saved'}, status=200)

todolist/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}| ToDo List</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

    <!-- Toastify JS/CSS-->
    <script src="https://cdn.jsdelivr.net/npm/toastify-js@1.12.0/src/toastify.min.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/toastify-js@1.12.0/src/toastify.min.css">

    
    
</head>
<body>

    {% include 'partials/_navbar.html' %}
    {% block content %} {% endblock %}




    


    

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.js" integrity="sha512-+k1pnlgt4F1H8L7t3z95o3/KO+o78INEcXTbnoJQ/F2VqDVhWoaiVml/OEHv9HsVgxUaVW+IbiZPUJQfF/YxZw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script>
    const showCustomToast = (message, color, duration = 3000) => {
        const toast = Toastify({
            text: message,
            style: {
                background: color,
                'border-radius': '10px',
            },
            className: "custom-toast",
            duration: duration,
            position: "center",
            close: true,
            stopOnFocus: true,
            
        });
    
        toast.showToast();  
    }
</script>
</body>
</html>

todolist/templates/index.html
{% extends 'base.html' %}
{% block styles %}
<style>
    .card-header {
        text-align: center;
        font-weight: bold;
    }
</style>
{% endblock %}
{% block title %} Dashboard {% endblock %}
{% block content %}
<main>

    <div class="sidebar">
        <ul class="nav nav-pills flex-column mb-auto">
            <div class="container-fluid mt-1 mb-1">
                <a href="/" class="text-decoration-none mb-0">
                    <span class="fs-4">Menu</span>
                </a>
            </div>
            <hr class="mt-0 mb-0">
            <li class="nav-item">
                <a href="{% url 'index' %}" class="nav-link active">Dashboard</a>
            </li>
            <li class="nav-item">
                <a href="{% url 'tasks' %}" class="nav-link">Task List</a>
            </li>
        </ul>
    </div>

    <div class="main-content dashboard">
        <h1>DASHBOARD</h1>
        <div class="row">
            {% for k,v in summary.items %}
            <div class="col-md-3 mb-3">
                <div class="card h-100 shadow ">
                    <div class="card-header task-status bg-{{k}}">{{k}}</div>
                    <div class="card-body">
                        <h1 class="text-center">{{v}}</h1>
                    </div>
                </div>
            </div>
            {% endfor %}


            <!-- <div class="col-md-3 mb-3">
                <div class="card h-100 shadow">
                    <div class="card-header bg-primary">In-Progress</div>
                    <div class="card-body">
                        {% for item in summary %}
                        {% if item.status == 'I' %}
                        <h1 class="text-center">{{item.id__count}}</h1>
                        {% endif %}
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div class="col-md-3 mb-3">
                <div class="card h-100 shadow">
                    <div class="card-header bg-success">Completed</div>
                    <div class="card-body">
                        {% for item in summary %}
                        {% if item.status == 'C' %}
                        <h1 class="text-center">{{item.id__count}}</h1>
                        {% endif %}
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div class="col-md-3 mb-3">
                <div class="card h-100 shadow">
                    <div class="card-header bg-danger">Cancelled</div>
                    <div class="card-body">
                        {% for item in summary %}
                        {% if item.status == 'CC' %}
                        <h1>{{item.id__count}}</h1>
                        {% endif %}
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div class="col-md-3 mb-3">
                <div class="card h-100 shadow">
                    <div class="card-header bg-secondary">Postponed</div>
                    <div class="card-body">
                        {% for item in summary %}
                        {% if item.status == 'PP' %}
                        <h1>{{item.id__count}}</h1>
                        {% endif %}
                        {% endfor %}
                    </div>
                </div>
            </div> -->
        </div>
        
    </div>

  </main>
{% endblock %}

todolist/templates/partials/_navbar.html
<nav class="navbar navbar-expand-lg">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">To Do List App</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <ul class="navbar-nav">
            <li class="nav-item" >Welcome, User!</li>
        </ul>
    </div>
</nav>

todolist/templates/task_list.html
{% extends 'base.html' %}
{% load static %}
{% block styles %}
<style>
    .card-header {
        text-align: center;
        font-weight: bold;
    }
</style>
{% endblock %}
{% block title %} Tasks {% endblock %}
{% block content %}
<main>

    <div class="sidebar">
        <ul class="nav nav-pills flex-column mb-auto">
            <div class="container-fluid mt-1 mb-1">
                <a href="/" class="text-decoration-none mb-0">
                    <span class="fs-4">Menu</span>
                </a>
            </div>
            <hr class="mt-0 mb-0">
            <li class="nav-item">
                <a href="{% url 'index' %}" class="nav-link">Dashboard</a>
            </li>
            <li class="nav-item">
                <a href="{% url 'tasks' %}" class="nav-link active">Task List</a>
            </li>
        </ul>
    </div>

    <div class="main-content dashboard">
        <h1>TASKS LIST</h1>
        <div class="controls">
            <button id="btnNew" class="btn btn-primary" data-toggle="modal" data-target="#newTaskModal">New</button>
        </div>
        <div class="table-responsive">
            <table class="table table-hover table-striped table-lg" id="taskTable" url-save-task="{% url 'save_task' %}">
                {% include 'task_table.html' %}

            </table>
        </div>

    </div>

</main>

<div class="modal fade" role="dialog" id="taskModal">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title"><span id="action"></span> Task</h5>
            </div>
            <div class="modal-body">
                <form action="" id="taskForm">
                    {% csrf_token %}
                    <input type="hidden" name="action">
                    <input type="hidden" name="taskId">
                    <div class="form-group">
                        <label for="">Title</label>
                        <input class="form-control" type="text" name="title" id="title" placeholder="Type a title..." required>
                    </div>
                    <div class="form-group">
                        <label for="">Description</label>
                        <textarea class="form-control" name="description" id="description" cols="30" rows="7" required></textarea>
                    </div>
                    <div class="form-group">
                        <label for="">Category</label>
                        <select class="form-control" name="category" id="category" required>
                            <option value="" selected="true" disabled>Select a category...</option>
                            {% for k,v in categories.items %}
                            <option value="{{k}}">{{v}}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <hr>
                    <div class="actions">
                        <button id="btnSave" class="btn btn-primary">Save</button>
                        <button id="btnCancel" class="btn btn-secondary">Cancel</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>


<div class="modal fade" role="dialog" id="deleteModal">
    <div class="modal-dialog modal-md">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Delete Task</h5>
            </div>
            <div class="modal-body">
                <form action="" id="deleteForm">
                    {% csrf_token %}
                    <input type="hidden" name="taskId">
                    <p>Please confirm to delete this task.</p>

                    <ul>
                        <li>
                            ID: <span id="taskId"></span>
                        </li>
                        <li>
                            Title: <span id="taskTitle"></span>
                        </li>
                    </ul>

                    <hr>
                    <div class="actions">
                        <button id="btnDeleteTask" class="btn btn-danger">Delete</button>
                        <button id="btnCancelDelete" class="btn btn-secondary">Cancel</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<script src="{% static 'js/tasklist.js' %}"></script>
{% endblock %}

todolist/templates/task_table.html
    <thead>
        <th>ID</th>
        <th>Title</th>
        <th>Description</th>
        <th>Category</th>
        <th>Status</th>
        <th>Created</th>
        <th>Modified</th>
        <th>Action</th>
    </thead>
    <tbody>
        {% for task in tasks %}
        <tr>
            <td>{{task.id}}</td>
            <td>{{task.title}}</td>
            <td>{{task.description}}</td>
            <td>{{task.get_category_display}}</td>
            <td>{{task.get_status_display}}</td>
            <td>{{task.created_on}}</td>
            <td>{{task.updated_on}}</td>
            <td>
                <button class="btn btn-warning" id="btnEdit">Edit</button>
                <button class="btn btn-danger" id="btnDelete">Delete</button>
            </td>
        </tr>
        {% endfor %}
    </tbody>